/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioDocIdRouteImport } from './routes/studio.$docId'
import { Route as ApiGenerateStencilRouteImport } from './routes/api/generate-stencil'
import { Route as ApiAiCopilotRouteImport } from './routes/api/ai-copilot'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioDocIdRoute = StudioDocIdRouteImport.update({
  id: '/studio/$docId',
  path: '/studio/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateStencilRoute = ApiGenerateStencilRouteImport.update({
  id: '/api/generate-stencil',
  path: '/api/generate-stencil',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCopilotRoute = ApiAiCopilotRouteImport.update({
  id: '/api/ai-copilot',
  path: '/api/ai-copilot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/vault': typeof VaultRoute
  '/api/ai-copilot': typeof ApiAiCopilotRoute
  '/api/generate-stencil': typeof ApiGenerateStencilRoute
  '/studio/$docId': typeof StudioDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/vault': typeof VaultRoute
  '/api/ai-copilot': typeof ApiAiCopilotRoute
  '/api/generate-stencil': typeof ApiGenerateStencilRoute
  '/studio/$docId': typeof StudioDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/vault': typeof VaultRoute
  '/api/ai-copilot': typeof ApiAiCopilotRoute
  '/api/generate-stencil': typeof ApiGenerateStencilRoute
  '/studio/$docId': typeof StudioDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/vault'
    | '/api/ai-copilot'
    | '/api/generate-stencil'
    | '/studio/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/vault'
    | '/api/ai-copilot'
    | '/api/generate-stencil'
    | '/studio/$docId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/vault'
    | '/api/ai-copilot'
    | '/api/generate-stencil'
    | '/studio/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  VaultRoute: typeof VaultRoute
  ApiAiCopilotRoute: typeof ApiAiCopilotRoute
  ApiGenerateStencilRoute: typeof ApiGenerateStencilRoute
  StudioDocIdRoute: typeof StudioDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$docId': {
      id: '/studio/$docId'
      path: '/studio/$docId'
      fullPath: '/studio/$docId'
      preLoaderRoute: typeof StudioDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-stencil': {
      id: '/api/generate-stencil'
      path: '/api/generate-stencil'
      fullPath: '/api/generate-stencil'
      preLoaderRoute: typeof ApiGenerateStencilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-copilot': {
      id: '/api/ai-copilot'
      path: '/api/ai-copilot'
      fullPath: '/api/ai-copilot'
      preLoaderRoute: typeof ApiAiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  VaultRoute: VaultRoute,
  ApiAiCopilotRoute: ApiAiCopilotRoute,
  ApiGenerateStencilRoute: ApiGenerateStencilRoute,
  StudioDocIdRoute: StudioDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
